### ISSUE TITLE
.dotProp not working

### ISSUE THREAD

**Issue by hdansou** [yoyurec/logseq-awesome-props#10]
**Info:**
- OS:
- Logseq ver: 0.8.17 Current Revision: [29da738-dirty](https://github.com/logseq/logseq/commit/29da738-dirty)
- Plugin ver: 0.1.4
- Theme name: Awesome Styler

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
.dotProps are not hidden anymore.

**To Reproduce:**
 add props `.dotProps:: something`

**Expected behavior:**
 Property with .dot to be hidden

**Comment by yoyurec** [comment]
fixed!
