### ISSUE TITLE
Awesome-Props hides all the properties in references

### ISSUE THREAD

**Issue by Gitbreast** [yoyurec/logseq-awesome-props#12]
**Info:**
- OS: MacOS
- Logseq ver: 0.8.17
- Plugin ver: 1.4.4
- Theme name: Null

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
Before:     <img width="150" alt="image" src="https://user-images.githubusercontent.com/96460796/220352319-0a9c860a-3775-4b1a-b865-65a5a77b7eda.png">        After: <img width="160" alt="image" src="https://user-images.githubusercontent.com/96460796/220351601-02308bc3-c37f-46d2-aa6c-403d1bdb9806.png">

**To Reproduce:**
Install Awesome Props.

**Expected behavior:**
 Props in references viewable.

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by huanhuanqiongqiong** [comment]
the same problem in windows 11

**Comment by yoyurec** [comment]
fiexd!
