### ISSUE TITLE
When customizing the icon of an attribute, if you enter Chinese pinyin, the input box will disappear.

### ISSUE THREAD

**Issue by huanhuanqiongqiong** [yoyurec/logseq-awesome-props#13]
**Info:**
- OS:windows 11
- Logseq ver: 0.8.17
- Plugin ver:1.5.3
- Theme name:

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
A clear and concise description of what the bug is......
When customizing the icon of an attribute, if you enter Chinese pinyin, the input box will disappear.
**To Reproduce:**
 ...
![image](https://user-images.githubusercontent.com/10186210/220833526-4f041532-9315-460f-806d-b97920218276.png)
in this box enter something in chinese, the box disappear
**Expected behavior:**
 ...

**Screenshots**

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
@huanhuanqiongqiong  can you provide me text. so i can copy-paste & check?
is it possible to record a video of "disappearing"?

**Comment by huanhuanqiongqiong** [comment]
![GIF 2023-2-24 9-23-39](https://user-images.githubusercontent.com/10186210/221069281-5398559b-4bc6-4a0c-a24a-313a67774f8e.gif)

**Comment by yoyurec** [comment]
looks like your virtual keyboard takes focus from field and it's hiding ((
need to think about solution...

**Comment by huanhuanqiongqiong** [comment]
hold the mouse left button will keep the input box from disappear

**Comment by yoyurec** [comment]
will redo layout
![image](https://user-images.githubusercontent.com/137919/221085846-034f23fd-6bdb-42dc-a60b-80c4039301d3.png)

**Comment by yoyurec** [comment]
fixed!
