### ISSUE TITLE
If the prop be hidden is the only one, a blank prop line would show up.

### ISSUE THREAD

**Issue by Gitbreast** [yoyurec/logseq-awesome-props#14]
**Info:**
- OS: macOS
- Logseq ver: 0.8.17
- Plugin ver: 1.5.3
- Theme name: null

- [x] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
If the prop be hidden is the only one, a blank prop line would show up.

**To Reproduce:**
Hide a prop, and type the prop name to a block or page, make sure it's the only one.

**Expected behavior:**
No blank line. 

**Screenshots**
<img width="489" alt="image" src="https://user-images.githubusercontent.com/96460796/220864991-bc866554-3d43-4538-986f-d7c78b48df26.png">
In this case I hide `tooo` and `toc`.
Editing:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/96460796/220865603-b6ae19b3-7b6c-43d4-b7a0-9db1c9baece6.png">
End editing:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/96460796/220865374-eb6b70f1-1750-45cb-8728-3513bd6d080f.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
yes ) it was always
as i'm not editing the core code of Logseq and working "on top of it", there are some limitations ((
no possibility to show Logseq "native placeholder", not good idea to hide it at all, code you will have no clickable zone...
![image](https://user-images.githubusercontent.com/137919/220882287-6f8b00d5-a906-4eac-85a1-df5676611399.png)

for now...

**Comment by Gitbreast** [comment]
@yoyurec Sorry for I'm not sure if I understood. I understood the clickable zone part. Is it possible to separate it in to 2 case? If it's not a pure property block (like my screenshots) then hide it, or it's a pure property block then show a line as a clickable zone?

**Comment by Gitbreast** [comment]
Btw in this case, I'm trying to use the `toc:: no` property to stop some blocks show in the `toc generator` plugin and trying to hide it XD

**Comment by yoyurec** [comment]
Logseq has props blocks. It has background color...
When you hide props via Logseq `config.edn` OR using predefined such as `icon:: ` and there is no other visible - Logseq shows "Properties" text (as on my screen) and not 'backgrounded-props-block',
I can't do same (at least now).

When plugin hides props lines it sone via CSS/JS, not Logseq system! So Logseq continue to think that there is/are prop(s) and shows it as styled block (((

not looking to who (Logseq/plugin) and how (placeholder text "Properties" / props block) doing this - you NEED to have something to click on to edit!
so i will not hide 'all-items-hidden-but-still-visible-props-colord-block' due UX

even if i mimic Logseq behavior - you will see same "noise" in your content - something like this
![image](https://user-images.githubusercontent.com/137919/220919586-808fcfd7-4210-48d8-ac1a-5efd726de376.png)

so a possible solution for you - hide blocks via `custom.css`, killing UX in honor of UI )))

**Comment by Gitbreast** [comment]
@yoyurec Thank you for the explanation now I understood, wish Logseq would have a better solution for this XDXD
