### ISSUE TITLE
it didn't support chinese, please add chinese support, thx!!

### ISSUE THREAD

**Issue by huanhuanqiongqiong** [yoyurec/logseq-awesome-props#2]
**Idea**

**Screenshots**
Add some pictures to get the idea if needed
![image](https://user-images.githubusercontent.com/10186210/219535321-12c03d27-ed32-46b1-8c67-90c50667dbf1.png)

**Attach files**
Add (via drag-n-drop) .zip with `.md` files if it help me with experiments

**Comment by yoyurec** [comment]
there was a bug with reading settings (((
check latest version!
