### ISSUE TITLE
FR: New icon for Health

### ISSUE THREAD

**Issue by hdansou** [yoyurec/logseq-awesome-props#4]
**Idea**
An icon for representing "health"

**Comment by yoyurec** [comment]
any ideas? )
https://tabler-icons.io/
![image](https://user-images.githubusercontent.com/137919/219827533-4d7111c8-7e41-420e-b289-908421e1b109.png)

![image](https://user-images.githubusercontent.com/137919/219827549-b7479581-736d-4e9d-8bcd-029becab77ca.png)

**Comment by yoyurec** [comment]
as for me, most generic is - https://tabler-icons.io/i/heartbeat
![image](https://user-images.githubusercontent.com/137919/219827674-2581dbce-5153-4cbf-ada5-5fe2def720a4.png)

**Comment by hdansou** [comment]
https://tabler-icons.io/i/heartbeat is a good choice. 
Secondary option: https://tabler-icons.io/i/activity

**Comment by yoyurec** [comment]
and the props that will use icon are ... ))

**Comment by hdansou** [comment]
health, workout

**Comment by yoyurec** [comment]
i think for workout need more "sportish" icon, than "medical"

**Comment by hdansou** [comment]
You already have this icon https://tabler-icons.io/i/stretching on there, maybe set the props name `workout` to it.
Good call!

**Comment by yoyurec** [comment]
https://discord.com/channels/725182569297215569/896368413243494430/1076536817387569182
