### ISSUE TITLE
FR: New icon for Community/group of people

### ISSUE THREAD

**Issue by hdansou** [yoyurec/logseq-awesome-props#5]
**Idea**
An icon for representing a group of people

**Comment by yoyurec** [comment]
sad, but there only 1 "normal", not "good" https://tabler-icons.io/i/users

**Comment by hdansou** [comment]
It seems that our only choice is https://tabler-icons.io/i/users.
Let's use it

**Comment by yoyurec** [comment]
and the prop(s) name(s) will be.... )

**Comment by hdansou** [comment]
team, community

**Comment by yoyurec** [comment]
https://discord.com/channels/725182569297215569/896368413243494430/1076536817387569182
