### ISSUE TITLE
FR: Collapsible Property

### ISSUE THREAD

**Issue by hdansou** [yoyurec/logseq-awesome-props#7]
**Idea**
Enable manual or automatic collapsible props grid in awesome Props plugin.

Alternatively, ensure collapsible props in plugin  https://github.com/vyleung/logseq-tidy-blocks-plugin works when using Awesome Props plugin.

**Comment by yoyurec** [comment]
> Alternatively, ensure collapsible props in plugin https://github.com/vyleung/logseq-tidy-blocks-plugin works when using Awesome Props plugin.

not possible on my side - need to update Tydi Blocks
