### ISSUE TITLE
FR: New Icon for measure

### ISSUE THREAD

**Issue by hdansou** [yoyurec/logseq-awesome-props#8]
**Idea**
Add a new icon

- Property name:
  - measure, metric, growth
- Property icon: 
  - https://tabler-icons.io/i/chart-line

**Comment by yoyurec** [comment]
measure - is a propcess.
metric - is a result of measuring
growth - is a positive metric 

it should be separate icons )))

**Comment by yoyurec** [comment]
`measure` - https://tabler-icons.io/i/ruler-measure
`metric`,`chart`,`propgress` - https://tabler-icons.io/i/chart-line
`growth`... will skip it for now...

**Comment by yoyurec** [comment]
https://discord.com/channels/725182569297215569/896368413243494430/1076536817387569182
