### ISSUE TITLE
FR: New Icon for map, navigation, location

### ISSUE THREAD

**Issue by hdansou** [yoyurec/logseq-awesome-props#9]
Idea
Add a new icon

- Property name:
  - map, navigation, location
- Property icon:
  - https://tabler-icons.io/i/map-2

**Comment by yoyurec** [comment]
have you checked already existing list? )
![image](https://user-images.githubusercontent.com/137919/219873994-c2cef480-f7c6-42c4-ad4b-deb7af752d0f.png)

**Comment by yoyurec** [comment]
keep in mind that the icon you like/suggest can be totally unreadable in a small 18x18 size!
